// <auto-generated />
using System;
using CardVault.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardVault.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardVault.Domain.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ColorIdentity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsLegendary")
                        .HasColumnType("boolean");

                    b.Property<int>("ManaValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Power")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PriceLastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subtype")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Supertype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Toughness")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("Cards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1d2e3f4-0000-0000-0000-000000000001"),
                            Artist = "Christopher Rush",
                            ColorIdentity = 0,
                            Description = "{T}, Sacrifice Black Lotus: Add three mana of any one color.",
                            ImageUrl = "https://cards.scryfall.io/large/front/b/d/bd8fa327-dd41-4737-8f19-2cf5eb1f7cdd.jpg",
                            IsLegendary = false,
                            ManaValue = 0,
                            Name = "Black Lotus",
                            Price = 500000.00m,
                            PriceLastUpdated = new DateTime(2026, 6, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Rarity = 3,
                            SetId = new Guid("a1b2c3d4-0000-0000-0000-000000000001"),
                            Supertype = "Artifact"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-0000-0000-0000-000000000002"),
                            Artist = "Matt Stewart",
                            ColorIdentity = 2,
                            Description = "At the beginning of your upkeep, look at the top card of your library. You may reveal that card. If an instant or sorcery card is revealed this way, transform Delver of Secrets.",
                            ImageUrl = "https://cards.scryfall.io/large/front/1/1/11bf83bb-c95b-4b4f-9a56-ce7a1816307a.jpg",
                            IsLegendary = false,
                            ManaValue = 1,
                            Name = "Delver of Secrets // Insectile Aberration",
                            Power = 1,
                            Price = 1.50m,
                            PriceLastUpdated = new DateTime(2026, 6, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Rarity = 1,
                            SetId = new Guid("a1b2c3d4-0000-0000-0000-000000000006"),
                            Subtype = "Human Wizard",
                            Supertype = "Creature",
                            Toughness = 1
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-0000-0000-0000-000000000003"),
                            Artist = "Simon Dominic",
                            ColorIdentity = 4,
                            Description = "Whenever Ragavan, Nimble Pilferer deals combat damage to a player, create a Treasure token and exile the top card of that player's library. Until end of turn, you may cast that card.",
                            ImageUrl = "https://cards.scryfall.io/large/front/a/9/a9738cda-adb1-47fb-9f4c-ecd930228c4d.jpg",
                            IsLegendary = true,
                            ManaValue = 1,
                            Name = "Ragavan, Nimble Pilferer",
                            Power = 2,
                            Price = 45.00m,
                            PriceLastUpdated = new DateTime(2026, 6, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Rarity = 4,
                            SetId = new Guid("a1b2c3d4-0000-0000-0000-000000000013"),
                            Subtype = "Monkey Pirate",
                            Supertype = "Legendary Creature",
                            Toughness = 1
                        });
                });

            modelBuilder.Entity("CardVault.Domain.Entities.CardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CardSets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000001"),
                            CardsCount = 295,
                            Code = "LEA",
                            ImageUrl = "https://svgs.scryfall.io/sets/lea.svg",
                            Name = "Limited Edition Alpha",
                            ReleaseDate = new DateTime(1993, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 1
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000002"),
                            CardsCount = 92,
                            Code = "ARN",
                            ImageUrl = "https://svgs.scryfall.io/sets/arn.svg",
                            Name = "Arabian Nights",
                            ReleaseDate = new DateTime(1993, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 2
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000003"),
                            CardsCount = 306,
                            Code = "MRD",
                            ImageUrl = "https://svgs.scryfall.io/sets/mrd.svg",
                            Name = "Mirrodin",
                            ReleaseDate = new DateTime(2003, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 2
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000004"),
                            CardsCount = 306,
                            Code = "RAV",
                            ImageUrl = "https://svgs.scryfall.io/sets/rav.svg",
                            Name = "Ravnica: City of Guilds",
                            ReleaseDate = new DateTime(2005, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 2
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000005"),
                            CardsCount = 249,
                            Code = "ZEN",
                            ImageUrl = "https://svgs.scryfall.io/sets/zen.svg",
                            Name = "Zendikar",
                            ReleaseDate = new DateTime(2009, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 2
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000006"),
                            CardsCount = 264,
                            Code = "ISD",
                            ImageUrl = "https://svgs.scryfall.io/sets/isd.svg",
                            Name = "Innistrad",
                            ReleaseDate = new DateTime(2011, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 2
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000007"),
                            CardsCount = 274,
                            Code = "RTR",
                            ImageUrl = "https://svgs.scryfall.io/sets/rtr.svg",
                            Name = "Return to Ravnica",
                            ReleaseDate = new DateTime(2012, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 2
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000008"),
                            CardsCount = 269,
                            Code = "KTK",
                            ImageUrl = "https://svgs.scryfall.io/sets/ktk.svg",
                            Name = "Khans of Tarkir",
                            ReleaseDate = new DateTime(2014, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 2
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000009"),
                            CardsCount = 269,
                            Code = "DOM",
                            ImageUrl = "https://svgs.scryfall.io/sets/dom.svg",
                            Name = "Dominaria",
                            ReleaseDate = new DateTime(2018, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 2
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000010"),
                            CardsCount = 264,
                            Code = "WAR",
                            ImageUrl = "https://svgs.scryfall.io/sets/war.svg",
                            Name = "War of the Spark",
                            ReleaseDate = new DateTime(2019, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 2
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000011"),
                            CardsCount = 269,
                            Code = "ELD",
                            ImageUrl = "https://svgs.scryfall.io/sets/eld.svg",
                            Name = "Throne of Eldraine",
                            ReleaseDate = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 2
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000012"),
                            CardsCount = 254,
                            Code = "MH1",
                            ImageUrl = "https://svgs.scryfall.io/sets/mh1.svg",
                            Name = "Modern Horizons",
                            ReleaseDate = new DateTime(2019, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 3
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000013"),
                            CardsCount = 303,
                            Code = "MH2",
                            ImageUrl = "https://svgs.scryfall.io/sets/mh2.svg",
                            Name = "Modern Horizons 2",
                            ReleaseDate = new DateTime(2021, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 3
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000014"),
                            CardsCount = 302,
                            Code = "NEO",
                            ImageUrl = "https://svgs.scryfall.io/sets/neo.svg",
                            Name = "Kamigawa: Neon Dynasty",
                            ReleaseDate = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 2
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000015"),
                            CardsCount = 281,
                            Code = "LTR",
                            ImageUrl = "https://svgs.scryfall.io/sets/ltr.svg",
                            Name = "The Lord of the Rings: Tales of Middle-earth",
                            ReleaseDate = new DateTime(2023, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SetType = 3
                        });
                });

            modelBuilder.Entity("CardVault.Domain.Entities.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Decks", (string)null);
                });

            modelBuilder.Entity("CardVault.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastActive")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("AccountName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CardVault.Domain.Entities.UserCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCards", (string)null);
                });

            modelBuilder.Entity("CardVault.Domain.Entities.Card", b =>
                {
                    b.HasOne("CardVault.Domain.Entities.CardSet", "Set")
                        .WithMany("Cards")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("CardVault.Domain.Entities.Deck", b =>
                {
                    b.HasOne("CardVault.Domain.Entities.User", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardVault.Domain.Entities.UserCard", b =>
                {
                    b.HasOne("CardVault.Domain.Entities.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CardVault.Domain.Entities.Deck", "Deck")
                        .WithMany("UserCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CardVault.Domain.Entities.User", "User")
                        .WithMany("UserCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardVault.Domain.Entities.CardSet", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("CardVault.Domain.Entities.Deck", b =>
                {
                    b.Navigation("UserCards");
                });

            modelBuilder.Entity("CardVault.Domain.Entities.User", b =>
                {
                    b.Navigation("Decks");

                    b.Navigation("UserCards");
                });
#pragma warning restore 612, 618
        }
    }
}
